export default {
  products: [
    {
      _id: 1,
      name: "slim Shirt",
      category: "shrits",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 2,
      name: "Fit Shirt",
      category: "shrits",
      image: "/images/d1.jpg",
      price: 70,
      brand: "louis",
      rating: 4.8,
      numReviews: 10,
    },
    {
      _id: 3,
      name: " Best Pants",
      category: "pants",
      image: "/images/d1.jpg",
      price: 55,
      brand: "jockey",
      rating: 5,
      numReviews: 10,
    },
    {
      _id: 4,
      name: " Best Pants",
      category: "pants",
      image: "/images/d1.jpg",
      price: 55,
      brand: "jockey",
      rating: 5,
      numReviews: 10,
    },
    {
      _id: 5,
      name: " Best Pants",
      category: "pants",
      image: "/images/d1.jpg",
      price: 55,
      brand: "jockey",
      rating: 5,
      numReviews: 10,
    },
  ],
};
